name: eulaiq
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.3
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_icons:
    git: https://github.com/jibiel/flutter-icons
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_spinkit: ^5.2.0
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.4
  logman: ^0.0.14
  path: ^1.8.2
  path_provider: ^2.0.3
  permission_handler: ^11.1.0
  riverpod_annotation: ^2.1.1
  share_plus: ^7.2.1
  shared_preferences: ^2.1.1
  uuid: ^4.2.2
  device_info_plus: ^10.1.2
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  material_design_icons_flutter: ^7.0.7296
  lottie: ^2.7.0

dependency_overrides:
  collection: ^1.17.2
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.3.4
  riverpod_generator: ^2.2.3
  lint: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/brand_assets/
    - assets/brand_assets/Eula_dipa.png
    - assets/brand_assets/Eula.png
    - assets/images/app-logo.png
